name: api
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./services/api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/servare-api:${{ github.sha }}
